name: hexlet-check

on:
  push:
    branches:
      - master

env:
  PROJECT_IMAGE: hexletprojects/js_l1_brain_games4_project

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hexlet project check
        uses: hexlet/project-action@master
        with:
          project_image: ${{ env.PROJECT_IMAGE }}
